version: "3.4"
x-logging:
  &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"

services:
  l2_execution_engine:
    image: gcr.io/mxczkevm/mxc-geth:mxc-wannsee-alpha3
    restart: unless-stopped
    pull_policy: always
    stop_grace_period: 3m
    volumes:
      - ./data/l2_execution_engine_data:/data/mxc-geth
    ports:
      - "${PORT_L2_EXECTION_ENGINE_METRICS}:6060"
      - "${PORT_L2_EXECTION_ENGINE_HTTP}:8545"
      - "${PORT_L2_EXECTION_ENGINE_WS}:8546"
      - "${PORT_L2_EXECTION_ENGINE_P2P}:30303"
      - "${PORT_L2_EXECTION_ENGINE_P2P}:30303/udp"
      - "${PORT_L2_EXECTION_ENGINE_AUTH_RPC}:8551"
    command:
      - --mxc
      - --networkid
      - "${CHAIN_ID}"
      - --syncmode
      - full
      - --gcmode
      - archive
      - --datadir
      - /data/mxc-geth
      - --metrics
      - --metrics.expensive
      - --metrics.addr
      - "0.0.0.0"
      - --bootnodes
      - ${BOOT_NODES}
      - --authrpc.addr
      - "0.0.0.0"
      - --authrpc.vhosts
      - "*"
      - --http
      - --http.api
      - debug,eth,net,web3,txpool,mxc
      - --http.addr
      - "0.0.0.0"
      - --http.vhosts
      - "*"
      - --http.corsdomain
      - "*"
      - --ws
      - --ws.api
      - debug,eth,net,web3,txpool,mxc
      - --ws.addr
      - "0.0.0.0"
      - --ws.origins
      - "*"
      - --rpc.txfeecap
      - "0"
    <<: *logging

  mxc_client_driver:
    image: gcr.io/mxczkevm/mxc-client:mxc-wannsee-alpha3
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l2_execution_engine
    volumes:
      - ./data/l2_execution_engine_data:/data/mxc-geth
    command:
      - driver
      - --l1.http
      - ${L1_ENDPOINT_HTTP}
      - --l1.ws
      - ${L1_ENDPOINT_WS}
      - --l2.ws
      - ws://l2_execution_engine:8546
      - --l2.auth
      - http://l2_execution_engine:8551
      - --mxcL1
      - ${MXC_L1_ADDRESS}
      - --mxcL2
      - ${MXC_L2_ADDRESS}
      - --jwtSecret
      - /data/mxc-geth/geth/jwtsecret
      - --p2p.syncVerifiedBlocks
      - --p2p.checkPointSyncUrl
      - 'https://wannsee-rpc.mxc.com'
    <<: *logging

  mxc_client_proposer:
    image: gcr.io/mxczkevm/mxc-client:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l2_execution_engine
      - mxc_client_driver
    env_file:
      - .env
    volumes:
      - ./script/start-proposer.sh:/script/start-proposer.sh
    entrypoint:
      - sh
      - "/script/start-proposer.sh"
    <<: *logging

  mxc_client_prover_relayer:
    image: gcr.io/mxczkevm/mxc-client:latest
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    depends_on:
      - l2_execution_engine
      - mxc_client_driver
      - zkevm-chain-prover-rpcd
    volumes:
      - ./script/start-prover-relayer.sh:/script/start-prover-relayer.sh
    entrypoint:
      - sh
      - "/script/start-prover-relayer.sh"
    <<: *logging

  zkevm-chain-prover-rpcd:
    image: gcr.io/mxczkevm/mxc-proverd:latest
    restart: unless-stopped
    ports:
      - "${PORT_ZKEVM_CHAIN_PROVER_RPCD}:9000"
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./script/start-zkevm-chain-rpcd.sh:/script/start-zkevm-chain-rpcd.sh
      - ./data/zkevm_chain_prover_rpcd_data:/data
    entrypoint:
      - sh
      - "/script/start-zkevm-chain-rpcd.sh"
    <<: *logging

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - ${PORT_PROMETHEUS}:9090
    depends_on:
      - l2_execution_engine
      - mxc_client_driver
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - ./data/prometheus_data:/prometheus
    command:
      - --log.level=debug
      - --config.file=/etc/prometheus/prometheus.yml
    <<: *logging

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - ${PORT_GRAFANA}:3000
    depends_on:
      - l2_execution_engine
      - mxc_client_driver
      - prometheus
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom/settings.ini
      - GF_PATHS_PROVISIONING=/etc/grafana/custom/provisioning
      - GF_LOG_LEVEL=WARN
    volumes:
      - ./docker/grafana/custom/settings.ini:/etc/grafana/custom/settings.ini
      - ./docker/grafana/custom/provisioning/:/etc/grafana/custom/provisioning/
      - ./data/grafana_data:/var/lib/grafana
    <<: *logging