x-logging: &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"

services:
  l2_execution_engine:
    image: us-docker.pkg.dev/mxczkevm/images/moonchain-geth:moonchain-mainnet
    build:
      context: ../mxc-geth
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    stop_grace_period: 3m
    volumes:
      - ./data/l2_execution_engine_data:/data/moonchain-geth
    ports:
      - "${PORT_L2_EXECUTION_ENGINE_METRICS}:6060"
      - "${PORT_L2_EXECUTION_ENGINE_HTTP}:8545"
      - "${PORT_L2_EXECUTION_ENGINE_WS}:8546"
      - "${PORT_L2_EXECUTION_ENGINE_P2P}:${PORT_L2_EXECUTION_ENGINE_P2P}"
      - "${PORT_L2_EXECUTION_ENGINE_P2P}:${PORT_L2_EXECUTION_ENGINE_P2P}/udp"
    command: |
      --mxc
      --networkid "${CHAIN_ID}"
      --gcmode archive
      --datadir /data/moonchain-geth
      --rpc.txfeecap "0"
      --metrics
      --metrics.addr "0.0.0.0"
      --bootnodes ${BOOT_NODES}
      --authrpc.addr "0.0.0.0"
      --authrpc.vhosts "*"
      --http
      --http.api debug,eth,net,web3,txpool,taiko,moonchain
      --http.addr "0.0.0.0"
      --http.vhosts "*"
      --ws
      --ws.api debug,eth,net,web3,txpool,taiko,moonchain
      --ws.addr "0.0.0.0"
      --ws.origins "*"
      --gpo.defaultprice "10000000"
      --port ${PORT_L2_EXECUTION_ENGINE_P2P}
      --discovery.port ${PORT_L2_EXECUTION_ENGINE_P2P}
      --maxpeers ${MAXPEERS:-50}
      --maxpendpeers ${MAXPENDPEERS:-0}
      --verbosity ${VERBOSITY:-4}
      ${GETH_ADDITIONAL_ARGS:-}
    <<: *logging
    profiles:
      - l2_execution_engine
      - prover
      - proposer

  moonchain_client_driver:
    image: us-docker.pkg.dev/mxczkevm/images/moonchain-client:moonchain-mainnet
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l2_execution_engine
    env_file:
      - .env
    volumes:
      - ./data/l2_execution_engine_data:/data/moonchain-geth
      - ./script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-driver.sh"
    <<: *logging
    profiles:
      - l2_execution_engine
      - prover
      - proposer

  moonchain_client_prover_relayer:
    image: us-docker.pkg.dev/mxczkevm/images/moonchain-client:moonchain-mainnet
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l2_execution_engine
      - moonchain_client_driver
    ports:
      - "${PORT_PROVER_SERVER}:9876"
    env_file:
      - .env
    volumes:
      - ./script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-prover-relayer.sh"
    <<: *logging
    profiles:
      - prover

  moonchain_client_proposer:
    image: us-docker.pkg.dev/mxczkevm/images/moonchain-client:moonchain-mainnet
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l2_execution_engine
      - moonchain_client_driver
    env_file:
      - .env
    volumes:
      - ./data/l2_execution_engine_data:/data/moonchain-geth
      - ./script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-proposer.sh"
    <<: *logging
    profiles:
      - proposer

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - ${PORT_PROMETHEUS}:9090
    depends_on:
      - l2_execution_engine
      - moonchain_client_driver
    volumes:
      - ./docker/prometheus/l2:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - --log.level=debug
      - --config.file=/etc/prometheus/prometheus.yml
    <<: *logging
    profiles:
      - l2_execution_engine
      - prover
      - proposer

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - ${PORT_GRAFANA}:3000
    depends_on:
      - l2_execution_engine
      - moonchain_client_driver
      - prometheus
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom/settings.ini
      - GF_PATHS_PROVISIONING=/etc/grafana/custom/provisioning
      - GF_LOG_LEVEL=WARN
    volumes:
      - ./docker/grafana/custom/settings.ini:/etc/grafana/custom/settings.ini
      - ./docker/grafana/custom/l2/provisioning/:/etc/grafana/custom/provisioning/
      - grafana_data:/var/lib/grafana
    <<: *logging
    profiles:
      - l2_execution_engine
      - prover
      - proposer

volumes:
  prometheus_data:
  grafana_data:
